### ISSUE TITLE
Exception while rendering map

### ISSUE THREAD

**Issue by Katrix** [BlueMap-Minecraft/BlueMap#12] opened 2020-01-15 18:17 UTC
Encountered this while rendering on of my maps.

```
Exception in thread "Thread-8" Exception in thread "Thread-9" java.lang.IllegalArgumentException: The box is degenerate on z
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
        at de.bluecolored.bluemap.core.util.AABB.<init>(AABB.java:92)
        at de.bluecolored.bluemap.core.util.AABB.<init>(AABB.java:60)
        at de.bluecolored.bluemap.core.render.hires.HiresModelManager.getTileRegion(HiresModelManager.java:124)
        at de.bluecolored.bluemap.core.render.TileRenderer.render(TileRenderer.java:49)
        at de.bluecolored.bluemap.cli.RenderTask.renderThread(RenderTask.java:162)
        at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalArgumentException: The box is degenerate on z
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
        at de.bluecolored.bluemap.core.util.AABB.<init>(AABB.java:92)
        at de.bluecolored.bluemap.core.util.AABB.<init>(AABB.java:60)
        at de.bluecolored.bluemap.core.render.hires.HiresModelManager.getTileRegion(HiresModelManager.java:124)
        at de.bluecolored.bluemap.core.render.TileRenderer.render(TileRenderer.java:49)
        at de.bluecolored.bluemap.cli.RenderTask.renderThread(RenderTask.java:162)
        at java.lang.Thread.run(Thread.java:748)
```

Not sure how I can get more information to help track down the cause, so opening this mostly just to inform that it happened, and get instructions on how to track down the issue.

**Comment by TBlueF** [comment] 2020-01-15 19:10
Did you configure some render-bounds in your map-config?
That might have caused that, i will look into this.

**Comment by Katrix** [comment] 2020-01-15 19:10
No render bounds

**Comment by TBlueF** [comment] 2020-01-18 11:26
This is confusing me on a new level rn .. xD

@Katrix 
Do you get this issue consistently? Does it render any of the world, or does it fail right away.
You don't have changed anything with the tile-size configs, right?

And .. does the world you are trying to render contains chunks with a really high or really low z-position?
Because the only way i can think of how this could happen is if there is some integer-overflow and infinity value stuff going on..

**Comment by Katrix** [comment] 2020-01-18 13:04
It just skips the world, and continues with the next one. Think it fails instantly. One of the worlds that are failing is a creative flat world if that makes any difference. Stuff from the creative world has also been copied into the other world that's failing.

**Comment by TBlueF** [comment] 2020-01-19 11:17
So i changed some things, but since i can not reproduce the error its quite difficult to say if that helps or makes it worse ^^
But if you still get an error, it will be a different one.
So if you want, you can download [this artifact](https://github.com/BlueMap-Minecraft/BlueMap/runs/397538097) (for 1.13+) or [this one](https://github.com/BlueMap-Minecraft/BlueMap/runs/397540611) (for 1.12), try it again and tell me if you are still getting an error.

**Comment by Katrix** [comment] 2020-01-19 12:51
Well, it didn't outright crash at least. I'll report back after it's done rendering if anything else broke instead.

**Comment by Katrix** [comment] 2020-01-19 13:20
So it worked, kind of. Problem is that there are huge holes in the map in some places.

![image](https://user-images.githubusercontent.com/11007080/72681715-2eb48080-3abe-11ea-8387-5af046ed280c.png)

Same map by DynMap
![image](https://user-images.githubusercontent.com/11007080/72681719-35db8e80-3abe-11ea-9f35-42dc4b2711be.png)

This also seems to happen in places that rendered fine previously (For some reason DynMap also has problems with that area, so might be something else)
![image](https://user-images.githubusercontent.com/11007080/72681727-47249b00-3abe-11ea-8457-e8745000fa85.png)

**Comment by TBlueF** [comment] 2020-01-19 13:29
Hmm, i fear the only way to track town this issue right now, is if i had a world where this happens to do some live debugging..

**Comment by Katrix** [comment] 2020-01-19 13:31
For the cases where it shows up as black now, but didn't before, or the world that just didn't render before?

**Comment by TBlueF** [comment] 2020-01-19 13:34
Well, anything that renders black but shouldn't would be great for the moment

**Comment by Katrix** [comment] 2020-01-19 13:43
A few months old, but think this one should work. https://mega.nz/#F!5hU2HCJC!IpwU8ZjpwSALOgLjoZtNlA?xlMBkYaR
Oh, also as a note. I'm rendering with caves enabled. No idea if that changes anything.

EDIT: Copied the wrong link. Fixed

**Comment by TBlueF** [comment] 2020-01-19 13:50
Thx, i will try this later

**Comment by Katrix** [comment] 2020-01-19 14:15
Some more info I found on this. When restarting the render after everything was done it found more chunks to render. Didn't fix the problem, but did improve it

**Comment by TBlueF** [comment] 2020-01-19 16:56
So.. for me all the 1.14 worlds rendered fine with the cli .. no unexpected black spots
Another question: do you have the problem only on the lowres models and when you zoom in the hires models get loaded?
Also, have you double checked that your browser is not caching anything?
The caches can be pretty obstinate, i often have to open the console and disable caching there to get the updated tiles ^^

Only issue i found was this:
![Anmerkung 2020-01-19 175516](https://user-images.githubusercontent.com/10765470/72684912-dd6bb780-3ae4-11ea-8e88-a7dd88a3ea0a.png)
But that is caused by the light-values not being calculated correctly on the world, i cant do much there..

**Comment by Katrix** [comment] 2020-01-19 18:05
So I just realized that many requests returned 403 results with the new jar. Seems like it was caused by some files not being gzipped. Is the default set correctly?

So, that solves the problem of why previously fine areas showed up as black with the new jar, but there is still the original maps that failed to render. Will try to get a world I can hand you that showcases those problems. Those did return 404, and not 403, but don't think there was any cases in the world I sent.

As for the shadow thing, think that has to do with those chunks not being loaded since we updated from 1.12.

**Comment by TBlueF** [comment] 2020-01-19 18:10
Alright, yea the gzip issue was my fault, already fixed it with 7fe60fa96d701eb4499a8b986eb3108f09467ce6.

If you get me an example for the other problem, i'll try that as well :)

**Comment by Katrix** [comment] 2020-01-19 20:38
https://1drv.ms/u/s!AujWrwEeDZYGlOtHX18gTFS8JHKZlg?e=p6oZJN

**Comment by TBlueF** [comment] 2020-01-19 21:27
Hmm, it is still rendering, but it seems to render even more than dynmap for me.. comparing it with your screenshots 🤔

![Anmerkung 2020-01-19 222440](https://user-images.githubusercontent.com/10765470/72688743-84af1580-3b0a-11ea-8b8f-be4a88e47c5b.png)

**Comment by TBlueF** [comment] 2020-02-04 21:05
Since i still can't reproduce this, i'll close this.
Feel free to reopen this if the issue persists and you have a possible way for me to reproduce it :)

**Closed as completed by TBlueF** 2020-02-04 21:05 UTC
Labels: bug
