### ISSUE TITLE
[Suggestion] Allow Mods to be used in the CLI version

### ISSUE THREAD

**Issue by AwesomeKalin** [BlueMap-Minecraft/BlueMap#467] opened 2023-08-17 14:41 UTC
I think this would be incredibly useful to those who use the CLI version and use it on worlds with mods. It shouldn't be hard to implement it, or at least to add an option to select the mods folder in the CLI version

**Comment by TBlueF** [comment] 2023-08-17 14:49
This is already planned, closing this as duplicate of #251 :)

**Closed as completed by TBlueF** 2023-08-17 14:49 UTC
Labels: duplicate

**Comment by TBlueF** [comment] 2023-08-17 14:55
I have been notified that i misunderstood the request. So, here is a correction:

You want to be able to have modded blocks.. etc. renderable with the CLI-version, which is easily possible already!
You can just copy/symlink the mods from your servers mod-folder into bluemaps `resourcepacks` folder. This will have the same effect as the plugin/mod does when loading them directly from the mods folder :)

As this is already possible, this issue remains closed ^^
