### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by untuned** [BlueMap-Minecraft/BlueMap#203] opened 2021-06-14 22:05 UTC
### What i did / Steps to reproduce
Updated to 1.5.3.

### Expected result
Not error on startup.

### Actual result
Errored on startup.

```
[18:03:38 ERROR]: [BlueMap] Failed to load!
java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.TimSort.mergeHi(TimSort.java:903) ~[?:?]
        at java.util.TimSort.mergeAt(TimSort.java:520) ~[?:?]
        at java.util.TimSort.mergeCollapse(TimSort.java:448) ~[?:?]
        at java.util.TimSort.sort(TimSort.java:245) ~[?:?]
        at java.util.Arrays.sort(Arrays.java:1515) ~[?:?]
        at java.util.ArrayList.sort(ArrayList.java:1750) ~[?:?]
        at de.bluecolored.bluemap.common.rendermanager.MapUpdateTask.createTasks(MapUpdateTask.java:79) ~[?:?]
        at de.bluecolored.bluemap.common.rendermanager.MapUpdateTask.<init>(MapUpdateTask.java:63) ~[?:?]
        at de.bluecolored.bluemap.common.rendermanager.MapUpdateTask.<init>(MapUpdateTask.java:59) ~[?:?]
        at de.bluecolored.bluemap.common.rendermanager.MapUpdateTask.<init>(MapUpdateTask.java:43) ~[?:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:185) ~[?:?]
        at de.bluecolored.bluemap.bukkit.BukkitPlugin.lambda$onEnable$0(BukkitPlugin.java:140) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Tuinity-"f32fe9a"]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Tuinity-"f32fe9a"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Tuinity-"f32fe9a"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[18:03:38 INFO]: [BlueMap] WebServer closed.
```

### Context
**BlueMap Version:**  
`1.5.3-spigot`

**Comment by TBlueF** [comment] 2021-06-14 23:03
You are not the only one with this issue ^^

Still i cannot reproduce this on my end somehow..

I pushed a tentative fix for this, could you maybe test [this build](https://github.com/BlueMap-Minecraft/BlueMap/runs/2824484950) if this fixes your issue? :)

**Comment by untuned** [comment] 2021-06-14 23:21
Still get the same error:
```
[19:20:47 INFO]: [BlueMap] Loading bluemap assets (1/3)...
[19:20:47 INFO]: [BlueMap] Loading realms assets (2/3)...
[19:20:47 INFO]: [BlueMap] Loading minecraft assets (3/3)...
[19:20:47 INFO]: [Lands] [Integrations] Successfully integrated Vault economy into economy system. Name: EssentialsX Economy Banks: true
[19:20:47 INFO]: [PlaceholderAPI] Successfully registered expansion: lands
[19:20:47 INFO]: [Lands] [Integrations] Successfully integrated PlaceholderAPI into chat system.
[19:20:47 INFO]: [Lands] [Integrations] Successfully integrated BlueMap into web system.
[19:20:47 INFO]: [Lands] [Integrations] Successfully integrated FastAsyncWorldEdit. 
[19:20:47 INFO]: [Lands] [Integrations] Successfully loaded LuckPerms contexts. More information: https://github.com/Angeschossen/Lands/wiki/Luckperms-Context
[19:20:48 ERROR]: [BlueMap] Failed to load!
java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.TimSort.mergeHi(TimSort.java:903) ~[?:?]
        at java.util.TimSort.mergeAt(TimSort.java:520) ~[?:?]
        at java.util.TimSort.mergeCollapse(TimSort.java:448) ~[?:?]
        at java.util.TimSort.sort(TimSort.java:245) ~[?:?]
        at java.util.Arrays.sort(Arrays.java:1515) ~[?:?]
        at java.util.ArrayList.sort(ArrayList.java:1750) ~[?:?]
        at de.bluecolored.bluemap.common.rendermanager.MapUpdateTask.createTasks(MapUpdateTask.java:86) ~[?:?]
        at de.bluecolored.bluemap.common.rendermanager.MapUpdateTask.<init>(MapUpdateTask.java:63) ~[?:?]
        at de.bluecolored.bluemap.common.rendermanager.MapUpdateTask.<init>(MapUpdateTask.java:59) ~[?:?]
        at de.bluecolored.bluemap.common.rendermanager.MapUpdateTask.<init>(MapUpdateTask.java:43) ~[?:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:185) ~[?:?]
        at de.bluecolored.bluemap.bukkit.BukkitPlugin.lambda$onEnable$0(BukkitPlugin.java:140) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Tuinity-"f32fe9a"]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Tuinity-"f32fe9a"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Tuinity-"f32fe9a"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[19:20:48 INFO]: [BlueMap] WebServer closed.
[19:20:50 INFO]: [Lands] You're using the latest version.
[19:20:52 INFO]: [Lands] Could not synchronize lands to BlueMap, because BlueMap's API doesn't seem to be enabled properly.
```

**Comment by TBlueF** [comment] 2021-06-14 23:22
damn .. alright, thanks

**Comment by TBlueF** [comment] 2021-06-15 12:42
Okay, second try would be [this build](https://github.com/BlueMap-Minecraft/BlueMap/runs/2829362218).
If you want to help, you could test this one as well :)

**Comment by untuned** [comment] 2021-06-15 18:19
> Okay, second try would be [this build](https://github.com/BlueMap-Minecraft/BlueMap/runs/2829362218).
> If you want to help, you could test this one as well :)

That worked!

**Comment by TBlueF** [comment] 2021-06-15 18:21
Awesome! :)
I'll close this then \o/

**Closed as completed by TBlueF** 2021-06-15 18:21 UTC
Labels: bug

**Comment by untuned** [comment] 2021-06-19 23:53
It seems that it's back again, @TBlueF.

```
[19:52:37 INFO]: [BlueMap] Loading bluemap assets (1/3)...
[19:52:38 INFO]: [BlueMap] Loading realms assets (2/3)...
[19:52:38 INFO]: [BlueMap] Loading minecraft assets (3/3)...
[19:52:38 INFO]: [Lands] [Integrations] Successfully integrated Vault economy into economy system. Name: EssentialsX Economy Banks: true
[19:52:38 INFO]: [PlaceholderAPI] Successfully registered expansion: lands
[19:52:38 INFO]: [Lands] [Integrations] Successfully integrated PlaceholderAPI into chat system.
[19:52:38 INFO]: [Lands] [Integrations] Successfully integrated BlueMap into web system.
[19:52:38 INFO]: [Lands] [Integrations] Successfully integrated FastAsyncWorldEdit. 
[19:52:38 INFO]: [Lands] [Integrations] Successfully loaded LuckPerms contexts. More information: https://github.com/Angeschossen/Lands/wiki/Luckperms-Context
[19:52:39 ERROR]: [BlueMap] Failed to load!
java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.TimSort.mergeHi(TimSort.java:903) ~[?:?]
        at java.util.TimSort.mergeAt(TimSort.java:520) ~[?:?]
        at java.util.TimSort.mergeCollapse(TimSort.java:448) ~[?:?]
        at java.util.TimSort.sort(TimSort.java:245) ~[?:?]
        at java.util.Arrays.sort(Arrays.java:1515) ~[?:?]
        at java.util.ArrayList.sort(ArrayList.java:1750) ~[?:?]
        at de.bluecolored.bluemap.common.rendermanager.MapUpdateTask.createTasks(MapUpdateTask.java:86) ~[?:?]
        at de.bluecolored.bluemap.common.rendermanager.MapUpdateTask.<init>(MapUpdateTask.java:63) ~[?:?]
        at de.bluecolored.bluemap.common.rendermanager.MapUpdateTask.<init>(MapUpdateTask.java:59) ~[?:?]
        at de.bluecolored.bluemap.common.rendermanager.MapUpdateTask.<init>(MapUpdateTask.java:43) ~[?:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:185) ~[?:?]
        at de.bluecolored.bluemap.bukkit.BukkitPlugin.lambda$onEnable$0(BukkitPlugin.java:140) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Tuinity-"f32fe9a"]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Tuinity-"f32fe9a"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Tuinity-"f32fe9a"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[19:52:39 INFO]: [BlueMap] WebServer closed.
[19:52:41 INFO]: [Lands] There is a new version available: 5.11.5
[19:52:43 INFO]: [Lands] Could not synchronize lands to BlueMap, because BlueMap's API doesn't seem to be enabled properly.
```

**Comment by TBlueF** [comment] 2021-06-19 23:55
@untuned Make sure you updated to 1.5.4 :)

**Comment by untuned** [comment] 2021-06-19 23:56
> @untuned Make sure you updated to 1.5.4 :)

That did in fact fix it, along with updating the plugin that uses the API (Lands). Thanks!
