### ISSUE TITLE
Bells arent displayed correctly

### ISSUE THREAD

**Issue by Jannik44** [BlueMap-Minecraft/BlueMap#540] opened 2024-05-12 12:30 UTC
![Screenshot_2024-05-12-14-28-13-943_org mozilla firefox](https://github.com/BlueMap-Minecraft/BlueMap/assets/76906033/f090ccf3-ba7d-4402-bacf-c0e92f7dc55b)

**Comment by TechnicJelle** [comment] 2024-05-12 12:32
This is already being worked on #145
It'll likely appear in the next major BlueMap update, in fact, thanks to the contributions of TyBraniff!

**Comment by TBlueF** [comment] 2024-05-12 12:32
Closing as duplicate of #145 :)

**Closed as completed** 2024-05-12 12:32 UTC
