### ISSUE TITLE
Map Render for Overworld is just Bedrock

### ISSUE THREAD

**Issue by jcpt928** [BlueMap-Minecraft/BlueMap#545] opened 2024-05-24 04:36 UTC
No offense to your ticket form; but, my issue is not that complex.

Debian 12, Sponge server for 1.20.6, no crazy server customization beyond Vanilla configuration, latest BlueMap version is the only mod, minimal modification of BleuMap map configuration. Nether rendering fine, End not yet visited, Overworld has a good amount of exploration - Overworld and End maps both render as bedrock with mushrooms.

**Comment by TBlueF** [comment] 2024-05-24 09:02
Soo, no offence to your issue complexity, but...

... i'll need some more info:
Are you using SpongeForge or SpongeVanilla, and which version exactly?
Whats the full BlueMap-version including the target? *(`latest` is not enough, and i'd need to know if you are using the sponge version or the forge version of bluemap)*
Your full overworld map-config file would be nice too.

*The ticket form would have included all of those ;)*

**Comment by jcpt928** [comment] 2024-05-24 14:09
Ha! It was about 1 AM; so, I wasn't all there. Irony is, I pulled in an old 1.<9 world, and that renders just fine! :P

The map I'm trying to get to render is from:

SpongeVanilla - 1.20.6-11.0.0-RC1618-universal
BlueMap - 3.21 for 1.20.6

[overworld.txt](https://github.com/BlueMap-Minecraft/BlueMap/files/15435613/overworld.txt)

**Comment by TBlueF** [comment] 2024-05-24 15:15
Thanks, so i can reproduce your issue. It's a bug in bluemap's map-id generation. 
That bug has been fixed in the newest snapshots already (since it does things completely differently there).

You can still make it work with your version on your end with a small trick:
BlueMap should have created 3 `bluemap.id` files in your `Gargantua` world-folder. one in `Gargantua` one in `Gargantua/DIM-1` and one in `Gargantua/DIM1`.
The problem is that the content of them is the same in each file, but it has to be different.

**So:** 
- Stop your server 
- open each of the `bluemap.id` files in a text-editor and replace the content with a couple of random letters
- Start your server again
- and purge the maps that have been generated wrongly

After that bluemap should start generating them correctly :)

One more side-note:
It is interesting that bluemap (almost) works on sponge-API 11 at all .. since it was compiled for sponge-API 8.2 (1.16.5) ^^

I will close this issue, as this bug does not exist in the snapshots and thus will be fixed with next full release as well :)

**Closed as completed by TBlueF** 2024-05-24 15:15 UTC
