### ISSUE TITLE
Players' position on the map isn't updating until relogging

### ISSUE THREAD

**Issue by SkarDeWitt** [BlueMap-Minecraft/BlueMap#345] opened 2022-09-28 23:57 UTC
### What i did / Steps to reproduce
Fresh setup of paper + bluemap, everything works perfectly, except for the players' head icon, which is not updating it's position unless the player re-logs 

### Expected result
I expected the position to update in real-ish time

### Actual result
Well, it didn't

### Context
**BlueMap Version:** BlueMap-3.4-spigot

Add more context here!
- Latest version of paper, windows 11
- Has the world been generated using any minecraft-mods? - Nnnope

Also:
- The issue is pretty self explanatory, but i can record a short vid if asked :)

**Comment by NNkGame** [comment] 2022-10-06 10:17
I had this problem too and I solved it somehow. You may check  if `live-player-markers:` is true, try uncomment  `write-players-interval:` in `plugin.conf` and restart server. Maybe it will help.

**Comment by TBlueF** [comment] 2023-01-16 05:49
Closing, as this is likely to be fixed in the latest version. (I can't reproduce it) 
Reopen (or comment) if this is still an issue :)

**Closed as completed by TBlueF** 2023-01-16 05:49 UTC
