### ISSUE TITLE
Some areas are missing

### ISSUE THREAD

**Issue by supsm** [BlueMap-Minecraft/BlueMap#136] opened 2021-01-17 04:29 UTC
**BlueMap Version: BlueMap-1.3.0-fabric-1.16.4**

I am using:
- 11 mods (on the rendered world)
- 0 resourcepacks (in bluemaps `config/resourcepack` folder)

**Description:**
Some places in the world map simply don't load, until I zoom in enough so that they are the high-res map.
To reproduce: open the map
Mods list: blcdisabler, bluemap, carpet extra, fabric api, carpet, fastfurnace, krypton, lithium, phosphor, spark, tic-tacs
I'm suspecting that it's probably tic-tacs, since it has been causing incompatibilities with many mods, and also changes chunk loading.
![image](https://user-images.githubusercontent.com/60897356/104830981-185c1480-5839-11eb-8c81-0699f850a012.png)

**Comment by supsm** [comment] 2021-01-17 05:14
Seems to be good now after a few restarts. I'll leave this open as it might come useful later

**Comment by TBlueF** [comment] 2021-01-17 09:17
Closing, since this is not a bug, but cached lowres-tiles.
Resolvable using the `clear tile cache` button in BlueMaps menu :)

**Closed as completed by TBlueF** 2021-01-17 09:17 UTC

**Comment by supsm** [comment] 2021-01-17 16:34
Thanks!
