### ISSUE TITLE
Exception in Thread, does not render at all

### ISSUE THREAD

**Issue by TNTUP** [BlueMap-Minecraft/BlueMap#61] opened 2020-07-25 07:08 UTC
Hi, first timer using Bluemap to test on my "scrap" 1.16.1 server and when I launch the render, it throws those errors and get stalled and no render or updates from BlueMap. > https://paste.md-5.net/ivadepukih.md

Server Version:
[0 03:06:11 INFO]: This server is running Paper version git-Paper-"0cf106087" (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[0 03:06:11 INFO]: Checking version, please wait...
[0 03:06:11 INFO]: Previous version: git-Paper-"42433c262" (MC: 1.16.1)
[0 03:06:11 INFO]: You are running the latest version

Windows Server 2019 x64 (JDK 8-251)

I could try running it as a standalone mode if that works, liked the idea to see tiles auto-updating with the plugin version

**Comment by TBlueF** [comment] 2020-07-25 07:23
The CLI Version should run into the same problem since the error is thrown when trying to read Biome-data from your world-files.
I assume there are no mods or anything installed if you are using paper.
Can you provide one of your region-files for me to be able to reproduce that issue?

**Comment by TNTUP** [comment] 2020-07-25 07:26
> The CLI Version should run into the same problem since the error is thrown when trying to read Biome-data from your world-files.
> I assume there are no mods or anything installed if you are using paper.
> Can you provide one of your region-files for me to be able to reproduce that issue?

I can say those chunks are coming from a converted 1.12.2 world, so I guess that might be the cause?

No mods but plugins `[0 03:24:32 INFO]: Plugins (21): BlueMap*, Essentials, EssentialsGeoIP, EssentialsSpawn, GetPlayerHeadName, HeadDatabase*, MentionNotifier*, OpenInv, PermissionsEx*, Pigasus*, PlugMan*, PramsPlayerCounter*, ProtocolSupport, ProtocolSupportStuff, spark, TNT*, TNTUProtect*, Vault, Wailat, WorldEdit, WorldGuard`

I'd send you one region file, doesn't tell me which one causes problems, I'll choose a random one: 
[r.-2.0.zip](https://github.com/BlueMap-Minecraft/BlueMap/files/4975037/r.-2.0.zip)

**Comment by TBlueF** [comment] 2020-07-25 07:45
So.. I rendered that file you sent me using the latest CLI.. and that worked fine .. i think .. that world is a mess though, is it supposed to look like that? xD

![image](https://user-images.githubusercontent.com/10765470/88451840-5c59f800-ce5a-11ea-8b9b-607afb32b011.png)

Anyways, the world looks heavily modified, i think somewhere some chunks have malformatted biomes.

Still this should not throw such an exception, and the render threads should not die from that. So i'd consider this a bug in Bluemap for not catching and handling that exception on the right place, so the render is able to continue after encountering an invalid chunk.

**Comment by TNTUP** [comment] 2020-07-25 09:01
Yes, thats part of my "scrap" server xD 

With *dynmap* it renders fine, but bluemap seems not, I guess the problem might be the first regions (r.0.1.mca or like that) but those stacktraces I given doesn't tell me what chunk or region it can't render.

**Comment by TBlueF** [comment] 2020-07-29 19:26
For the record: I actually found a bug that caused this..
So its not the worlds fault, but just the fact that bluemap was confused that there are actually water-blocks at y:255 ^^
Should be fixed with a33dda0a29514149d7ca20f766940c7af38c3dad.

**Closed as completed by TBlueF** 2020-07-29 19:26 UTC
Labels: bug

**Comment by TNTUP** [comment] 2020-07-30 01:42
I can confirm it now renders fine <3
