### ISSUE TITLE
Add MongoDB or SQL database Support

### ISSUE THREAD

**Issue by mrsolarius** [BlueMap-Minecraft/BlueMap#217] opened 2021-07-15 09:05 UTC
As a server owner, I make a lot of backups of my map and my server. But with the blue map, I can't. The number of files generated by the blue map takes too much time to be backup in one night.

So to solve these two problems, I propose to make the blue map data savable inside a database. SQL database or MongoDB database. I think mongo DB is more adapted to save the blue map data schemas because there is no join at all and actually it's save in JSON like in MongoDB.
 I know that you want the blue map the lightest as possible so I think the best way to achieve that is to create a NodeJS app for the website. This app could be easily run from java using the os command without any prerequisite or system configuration instead of NodeJS.

Thanks a lot for all of your work to develop this awesome map.
Hop this feature could interest you.

**Comment by Seercat3160** [comment] 2021-07-15 09:28
Possible duplicate of #80.

**Comment by mrsolarius** [comment] 2021-07-15 10:01
Yes for the SQL server but for MongoDB it's not ^^'
So I edit my issue for MongoDB only?

**Comment by TBlueF** [comment] 2021-07-15 10:09
I added a note for MongoDB on the other Ticket and will close this in favour of the other one :)

**Closed as completed by TBlueF** 2021-07-15 10:09 UTC

**Comment by mrsolarius** [comment] 2021-07-15 12:05
Thanks :) !
