### ISSUE TITLE
[dev host] Rendering doesnt work...right? Only on certain aspects within the low-res layer

### ISSUE THREAD

**Issue by Merith-TK** [BlueMap-Minecraft/BlueMap#318] opened 2022-08-11 16:22 UTC
### What i did / Steps to reproduce
I just flew around on
https://bluecolored.de/bluemap-dev/
till I found something, testing its performance
### Actual result
https://bluecolored.de/bluemap-dev/#world:1121:174:1580:0:2.23:1.33:0:0:free

the Super Low Res layer renders beyond the horizon while the low res layer is actively visible

I am using brave browser, and the issue persists without brave shields

**Comment by TBlueF** [comment] 2022-08-11 16:26
Known issue :)
But thanks! ^^

**Comment by TBlueF** [comment] 2022-08-11 16:28
Explanation for the curious:
It's caused by the cave that makes the height-map go below y0 at one point .. the height-map will support that but doesn't yet :)

**Comment by TBlueF** [comment] 2022-08-15 07:35
Should be Fixed :)

**Closed as completed by TBlueF** 2022-08-15 07:35 UTC
