### ISSUE TITLE
Carpet players dont leave the players in the webapp

### ISSUE THREAD

**Issue by PeHeReBe** [BlueMap-Minecraft/BlueMap#603] opened 2024-09-02 17:21 UTC
### What i did / Steps to reproduce
- Create a "fake" player with carpet mod (/player [name] spawn)
- let the fake player leave (killing it)

### Expected result
- Players will leave the "Players" tab in the webapp

### Actual result
- Fake Players even when left the server still vissible in the webapp

### Context
**BlueMap Version:**  
`fabric 5.3 1.21`

### Add more context here!
- "Vanilla" Server only QOL Mods on fabric.
- Server is running on Debian
- Server using LazyMC but BlueMap is running on nginx -> (nignx file on Discord in Supportchannel from Lukas/Blue)
- NPC player "Villager" is even from a previous session with the server sleeping in between

Also:
- No Log

![grafik](https://github.com/user-attachments/assets/43beb866-376d-4dc6-9376-be766d58dd72)
![grafik](https://github.com/user-attachments/assets/0c18700e-ce63-4d9c-aea8-01c47a0b59e7)
![grafik](https://github.com/user-attachments/assets/466df77a-4a1c-4346-aff6-73dd5bdb8271)

Thx have a nice day

**Comment by TechnicJelle** [comment] 2024-09-02 17:23
Duplicate of #598, I believe

**Closed as not planned** 2024-09-02 17:23 UTC
Labels: duplicate

**Comment by TBlueF** [comment] 2024-09-02 17:25
See #598 for more info :)
