### ISSUE TITLE
[Suggestion] External storage options

### ISSUE THREAD

**Issue by BastionNtB** [BlueMap-Minecraft/BlueMap#256] opened 2021-11-19 04:32 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Why do you want this feature

Would be nice to have the option to store the map json files externally

**Describe the solution you'd like**

A configuration setting to point to a UNC path of where the map files are stored.

I know there is an option to run the web server externally, but I believe all the files are run locally on the minecraft server, and you lose some features when doing this.

**Comment by subzero** [comment] 2021-11-19 10:49
Feature is already there.

Please follow the wiki at https://bluemap.bluecolored.de/wiki/getting-started/Configuration.html#webserver-configuration-webserverconf

You state the external webroot for Bluemap to dump it's worldrender.
You do so in both the webserver.conf and render.conf

**Comment by TBlueF** [comment] 2021-11-19 11:02
I have not tested it, but you should be able to use UNC-paths as your webroot as well :)

**Comment by TBlueF** [comment] 2021-11-22 21:46
@DatsiK96 Closing this, since i believe UNC-paths should work already.
Please reopen this if they don't work for you. Including a description on how to reproduce that issue :)

**Closed as completed by TBlueF** 2021-11-22 21:46 UTC
