### ISSUE TITLE
Improve Marker performance

### ISSUE THREAD

**Issue by Zottelchen** [BlueMap-Minecraft/BlueMap#600] opened 2024-08-19 00:03 UTC
(Not entirely sure if this counts as bug or feature request.)

### What i did / Steps to reproduce
1. I rendered a map
2. I added a whole lot of markers (~8MB marker file)
3. I opened the map

### Expected result
I can use a lot of markers smoothly. (This was not an issue with leaflet maps, but Bluemaps is admittedly cooler :))

### Actual result
Everything is slow. See for yourself https://map.drehmal.cyou/

### Context
**BlueMap Version:** Docker/CLI: ghcr.io/bluemap-minecraft/bluemap:latest (Should be 5.3, webpage says 5.2 though)

**Comment by TBlueF** [comment] 2024-08-19 06:12
I will definitely consider marker-performance with the webapp-rewrite that i want to do and #244.

Duplicate of #558
Closing because of [this](<https://github.com/BlueMap-Minecraft/BlueMap/blob/d5fe7175c661e3e9e679009199e29d3d758e5528/.github/CONTRIBUTING.md#suggesting-a-new-feature-or-change:~:text=will%20be%20closed!-,Suggesting%20a%20new%20feature%20or%20change,-Please%20use%20our>) :)

**Closed as completed by TBlueF** 2024-08-19 06:12 UTC
