### ISSUE TITLE
BlueMap block texture swap

### ISSUE THREAD

**Issue by GrandmaPork** [BlueMap-Minecraft/BlueMap#342] opened 2022-09-27 17:43 UTC
### What i did / Steps to reproduce
Loaded bluemap area with two polished blackstone slabs combined into a block

### Expected result
A correctly rendered block 

### Actual result
The block sides were replaced with Macaw's spruce paper trapdoor top 

### Context
**BlueMap Version:** 
`3.4-forge-1.18.2`

- The used os and platform: Windows, Forge
- Has the world been generated using any minecraft-mods? 110 other mods. 
- Only issue I've found like this so far
- 
![BlueMap - Overworld - Opera 9_27_2022 1_35_57 PM](https://user-images.githubusercontent.com/109642282/192598734-58bb5339-1bbe-4043-80ae-688a79166500.png)

**Comment by TBlueF** [comment] 2022-10-13 18:15
![image](https://user-images.githubusercontent.com/10765470/195666526-9efaecc5-f6e0-4a04-86a7-4df5c7d7aaec.png)
I can't reproduce this, that block is rendering fine on my end..

What i can reproduce is, that a block that should render the "missing-texture"-texture (pink/black checkered) is rendering a random other texture, in your case the "Macaw's spruce paper trapdoor top"-texture..
I fixed this in 06c97b74c1db548086b96e029f8bac06c8024875

I'll close this issue because i can't reproduce it. If you find a better way to reproduce this, you can reopen it with the steps explained :)

**Closed as completed by TBlueF** 2022-10-13 18:15 UTC
Labels: needs testing
