### ISSUE TITLE
Load biome info from datapacks

### ISSUE THREAD

**Issue by PortableGames** [BlueMap-Minecraft/BlueMap#272] opened 2021-12-12 11:59 UTC
try to load biome-infos from datapacks for correct display of block color on map

![Screenshot_20211206-182005](https://user-images.githubusercontent.com/89090940/145711269-8fae342d-7bb9-4b4b-873e-8f1ae5379111.png)

used datapack: https://www.planetminecraft.com/data-pack/terralith-overworld-evolved-100-biomes-caves-and-more/

**Comment by PortableGames** [comment] 2021-12-21 07:39
I found this can be used as a temporary solution: https://github.com/StrangeOne101/Datapack-Bluemap-Generator

**Comment by PortableGames** [comment] 2021-12-21 09:30
![Screenshot_20211221-102743](https://user-images.githubusercontent.com/89090940/146906015-4b9df0ca-989e-4aac-abb7-3a9cc05d9341.png)

**Comment by TBlueF** [comment] 2022-01-16 12:00
Closing this, as it is a duplicate of #156

**Closed as completed by TBlueF** 2022-01-16 12:00 UTC
