### ISSUE TITLE
Server crashes every night

### ISSUE THREAD

**Issue by Plop** [BlueMap-Minecraft/BlueMap#363] opened 2022-12-15 07:50 UTC
### What i did / Steps to reproduce

- Install Bluemap
- Run PaperMC server
- Crash happens during the night, with or without any player logged in

When I disable the plugin, no crash happens.

I tried 

### Expected result

Server running fine without any crash

### Actual result

Server crashing every night

### Context
**BlueMap Version:**  
`1.0.0-fabric-1.16.1`

BlueMap-3.7-spigot

paper-1.19.2-307
Debian GNU/Linux 10 (buster)
No world generation with any mod. The server is almost full vanilla, but the crash happens even when I disable every other plugins beside Bluemap.

Full error log in the attached file
[error_log.txt](https://github.com/BlueMap-Minecraft/BlueMap/files/10234875/error_log.txt)

Thank you for your help

**Comment by TBlueF** [comment] 2022-12-15 13:02
Looks like somehow a tick took way too long and the watchdog stopped the server..

According to your log, BlueMap was doing nothing at that moment other than trying to load a player-skin of a player that just joined. All of that is not running on the server-thread so there couldn't be anything really that would trigger the watchdog.

----

Can you please **also send the error logs of the other crashes**? To see if there are any obvious similarities between them.

And - since this was bluemaps only activity at the time of the crash - you could try and turn off bluemap's skin-grabber by setting `skin-download: false` in the `plugin.conf`. And see if it still crashes. I don't think this is the issue, but it's worth a try :)

**Comment by Plop** [comment] 2022-12-17 19:20
Hi,

Thank your for your answer. Here are other logs : 

[2022-12-13-1.log](https://github.com/BlueMap-Minecraft/BlueMap/files/10252515/2022-12-13-1.log)
[2022-12-14-2.log](https://github.com/BlueMap-Minecraft/BlueMap/files/10252516/2022-12-14-2.log)
[2022-12-14-1.log](https://githubcom/BlueMap-Minecraft/BlueMap/files/10252522/2022-12-14-1.log)

I disabled skin-download tonight and will see if the issue happens again, but the server crashes even if no one is connected for days.

**Comment by TBlueF** [comment] 2022-12-17 21:10
Okay, all of those logs show completely different game-stages, in only one of them BlueMap was rendering something..
E.g. in [2022-12-14-2.log](https://github.com/BlueMap-Minecraft/BlueMap/files/10252516/2022-12-14-2.log), BlueMap is not doing anything at all.

My guess would be that your Garbage-Collector is stopping the whole thing for too long, because you give your Server too much RAM.. which then triggers the Watchdog and is stopping the server.
The only role BlueMap plays in this, would then be that BlueMap is giving your server a "reason" to accumulate the amounts of RAM that is enough to cause this huge lagspike. Which would not be a BlueMap issue, but a problem with your JVM-arguments ^^

This is just a guess rn, could this be true? How much RAM **are** you giving your JVM? :)

**Comment by Plop** [comment] 2022-12-17 21:15
There is 8Go of RAM on my server, and my Xms and Xmx is 2Go. I'm not sure if that's good ?

**Comment by TBlueF** [comment] 2022-12-17 21:20
Welp .. no, that's not much at all ..
Then i am out of ideas tbh.

I definitely can not find any reason why BlueMap would be causing this :/
It's also not something i can reproduce..

**Comment by TBlueF** [comment] 2023-01-16 05:46
Closing as this could not be reproduced

**Closed as completed by TBlueF** 2023-01-16 05:46 UTC
