### ISSUE TITLE
Bluemap 3.4 Unable to load player head

### ISSUE THREAD

**Issue by yf639898** [BlueMap-Minecraft/BlueMap#343] opened 2022-09-28 07:12 UTC
The web map cannot load player head, the default head are obtained
Versions 3.3 and later are available
![](https://user-images.githubusercontent.com/76139891/192712473-911b77a2-48ff-462f-896c-36e7fd3b024c.png)

**Comment by yf639898** [comment] 2022-09-28 07:30
使用了服务器至NAS的存储方案。
The server to NAS storage solution is used.
webapp：Z:\\...\\Asgard_1.19.2_2022-09-27_Map\\bluemap
webserver：Z:\\...\\Asgard_1.19.2_2022-09-27_Map\\bluemap
file：Z:\\...\\Asgard_1.19.2_2022-09-27_Map\\bluemap\\maps
均导向至NAS进行存储后调用web服务。
All of this is directed to the NAS for storage, and then the file forwarding Web service is invoked using the server.
BlueMap3.4，在1.19.2paper及forge服务端都复现玩家头像无法获取404
BlueMap3.4, in 1.19.2 both paper and Forge server player head cannot get 404

**Comment by TBlueF** [comment] 2022-09-28 07:42
Duplicate of: https://github.com/BlueMap-Minecraft/BlueMap/issues/330

A temporary fix for this would be to manually sync `./bluemap/assets/playerheads` from one of the servers to your webroot.

( Closing this in favor of #330 )

**Closed as completed by TBlueF** 2022-09-28 07:42 UTC
Labels: duplicate
