### ISSUE TITLE
Online Player Sidebar

### ISSUE THREAD

**Issue by ErythroCraft** [BlueMap-Minecraft/BlueMap#166] opened 2021-02-25 11:26 UTC
The issue is simple. But not simple to create manualy.

In the picture you'll see an sidebar on the right-side.
Maybe you can give an update for an player sidebar to see the onlineplayer.

The issue:
• Sidebar fixed (no open button)
• Animated fields - 
  [ online player - move in ]
  [ offline player - move out ]
• Clickable player fields to see %placeholder%
  [ placeholder config file ] or [ addable in .js file ]

For customs:
• player_sidebar.json
• placeholder.json

![bluemap-player-sidebar](https://user-images.githubusercontent.com/76217862/109146847-9b3f8b80-7764-11eb-93a5-131dd1432ef4.png)

**Comment by TBlueF** [comment] 2021-02-25 11:54
Correct me if i am wrong, but if i understood you correctly this is a duplicate of #96 ? :)

**Comment by ErythroCraft** [comment] 2021-02-25 12:11
No problem. It's just an idea.

**Comment by TBlueF** [comment] 2021-02-25 12:15
Its a good Idea! And its already planned to add a playerlist! I'll close this issue, but its linked in the original issue #96 where the discussion about this feature can be continued :)

**Closed as completed by TBlueF** 2021-02-25 12:15 UTC
