### ISSUE TITLE
Custom Biome Colours don't function as intended on Webmap

### ISSUE THREAD

**Issue by BirbEXE** [BlueMap-Minecraft/BlueMap#296] opened 2022-03-05 11:55 UTC
### What i did / Steps to reproduce
generate a world with IRIS world generator: https://github.com/VolmitSoftware/Iris
go to a custom biome that uses custom colours for leaves / etc
look on map: colours will be default minecraft colours, instead of the custom ones shown in-game

### Expected result
the colours to be the same as in game

### Actual result
the colours were generated by default minecraft

### Context
**BlueMap Version:**  --> BlueMap-1.7.2-spigot.jar
running on `purpur-1.18.2-1574`

### Additional info
- Hosted on pterodactyl panel.
- The world is using no mods, only plugins. the custom world generator changes block colours with custom biomes
- The map works as intended, it's just the colours that are off

**Comment by BirbEXE** [comment] 2022-03-05 12:14
screenshots didn't load above: 
in game = ![2022-03-05_11 52 40](https://user-images.githubusercontent.com/60234159/156881941-58b9908a-e0f1-4a02-97fa-db5728bebd68.png)

webmap = 
![image](https://user-images.githubusercontent.com/60234159/156882138-148b4dcb-76a6-467f-b6c1-e2220d6efc24.png)

**Comment by TBlueF** [comment] 2022-03-05 12:24
Closing, because its a duplicate of #156 

Might help you:
https://bluemap.bluecolored.de/wiki/customization/Mods.html#biomes-config
https://github.com/StrangeOne101/Datapack-Bluemap-Generator

**Closed as completed by TBlueF** 2022-03-05 12:24 UTC
