### ISSUE TITLE
Multi servers support

### ISSUE THREAD

**Issue by TheCalypso** [BlueMap-Minecraft/BlueMap#143] opened 2021-01-25 22:48 UTC
**Is your feature request related to a problem? Please describe.**
Hello,
Congratulations for the work you have done is really great!
Being the admin of a minecraft network our community thought that it might be nice to be able to use the plugin on several servers but to have a single web access to have everything in one place.

**Describe the solution you'd like**
For this a support by database would probably be the most suitable. People with several dedicated machines could use this system and also people with only one machine but several servers on it. The plugin should therefore be a "proxy" mode and a "follower" mode.

**Comment by TBlueF** [comment] 2021-01-26 00:06
Hey,
what you are describing is already planned :)

There is #138 which is the first step to make maps rendered with BlueMap fully transferrable to other web-app's. With that you'll already (without database support) be able to use e.g. rsync or nfs or an nginx reverse-proxy to setup maps from multiple servers on one webapp.

And then there is #80 which adds support for MySQL and maybe even more databases :)

Both are some bigger changes/features that will probably take some more time until they are done, however i am already working on a web-app rewrite that includes big preparations for #138 :) 

I am not doing ETA's or promises, but [this TODO](https://github.com/BlueMap-Minecraft/BlueMap/projects/1) has the currently planned steps listed in rough order =)

*(Closing this, just because its basically a duplicate of #138 and #80)*

**Closed as completed by TBlueF** 2021-01-26 00:06 UTC

**Comment by TheCalypso** [comment] 2021-01-26 06:10
oh that's really great!  yes so at the moment i can't do it too much without going through an rsync with a script.  but that's okay I'll wait for these great features to arrive!  Congratulations again for the work you do!
