### ISSUE TITLE
Area markers show under the rendered map

### ISSUE THREAD

**Issue by ItsEverest** [BlueMap-Minecraft/BlueMap#386] opened 2023-01-31 12:51 UTC
### What i did / Steps to reproduce
Add area markers in the world config file
### Expected result
Area showing over the rendered map

### Actual result

![image](https://user-images.githubusercontent.com/78271762/215764143-6ca50691-3501-4591-b3ac-5bbc2a361d95.png)
Area shows under the rendered map
### Context
**BlueMap Version:**  
3.5 Beta 1

<!-- 
Add more context here!
- The used os and platform (Windows/Linux, Spigot/Paper/Forge/Fabric/Sponge)
Windows
- Has the world been generated using any minecraft-mods?
Terra Plugin

**Comment by TBlueF** [comment] 2023-01-31 12:59
Is the shape-markers `depth-test` property set to `false` ?
Otherwise this is intended behavior :)

**Comment by TBlueF** [comment] 2023-02-01 20:45
Assuming it was set to `true` (default), I'll close this until there is a response saying otherwise :)

**Closed as completed by TBlueF** 2023-02-01 20:45 UTC
