### ISSUE TITLE
网页地图中方块的错误 Errors of blocks in WebMap

### ISSUE THREAD

**Issue by zichenace** [BlueMap-Minecraft/BlueMap#362] opened 2022-12-05 23:59 UTC
服务器版本/Server version：1.19.2.300（papermc）
问题：含水台阶无法正常显示，水方块与台阶发生了冲突。
Problem: The waterlogged stairs cannot be displayed normally, and the water block conflicts with the stairs.

![1](https://user-images.githubusercontent.com/79037972/205771885-f21b727e-bf01-4c5e-975e-d7bd6b4cafe6.png)

**Comment by TBlueF** [comment] 2022-12-06 08:32
Duplicate of #97

**Closed as completed by TBlueF** 2022-12-06 08:32 UTC
Labels: duplicate
