### ISSUE TITLE
Optimized 2D Render

### ISSUE THREAD

**Issue by AngellusMortis** [BlueMap-Minecraft/BlueMap#196] opened 2021-05-25 18:19 UTC
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

The 3D render of Bluemap is easily the best reason why Bluemap is better then old solutions (i.e. Dynmap), but the 3D render using WebGL is very resource intensive on the Web browser. It would be great to have a perspective/layer/whatever that works more like the other solutions. Basically take the "Flat" perspective and render static images and return those and render them instead of JSON objects of the whole chunk that needs to be rendered via WebGL. 

This would...

* Help users with low end machines/phones trying to use the Web interface
* Allow for "fast" exploration to load a lot of land really fast to explore/look around with the static 2D Web map and then switch to 3D mode to really dig in and look around. It can take a really long time to render a lot of chunks in high res 3D mode and it makes it really hard to "explore" the map with Bluemap.

**Comment by TBlueF** [comment] 2021-06-07 21:41
Closing because its basically a duplicate of #3 :)

**Closed as completed by TBlueF** 2021-06-07 21:41 UTC
