### ISSUE TITLE
Hide command - Hide yourself on the map

### ISSUE THREAD

**Issue by he3als** [BlueMap-Minecraft/BlueMap#173] opened 2021-03-10 19:11 UTC
**Is your feature request related to a problem? Please describe.**
Yes, many people on my server have secret chests/bases, and the maps just reveal the location.

**Describe the solution you'd like**
Make a command (/bluemap hide) for everyone to use to hide themselves on the map.

**Comment by TBlueF** [comment] 2021-03-12 09:24
Closing, because this is a duplicate of #75 :)

**Closed as completed by TBlueF** 2021-03-12 09:24 UTC
